    function y = logPostPDF(B, sigma, threshold, delay, thresholdvar, ...
        meanThreshold, varThreshold, Y, LX)
      y = threshold.logLik(B, sigma, threshold, delay, thresholdvar, Y, LX) + ...
          threshold.logPriorPDF(threshold, meanThreshold, varThreshold);
    end
