    function y = logPostPDF(B, sigma, th, delay, thresholdvar, ...
        meanThreshold, varThreshold, Y, LX)
      y = threshold.logLik(B, sigma, th, delay, thresholdvar, Y, LX) + ...
          threshold.logPriorPDF(th, meanThreshold, varThreshold);
    end
